# Generated by Django 3.1.14 on 2024-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
