# Generated by Django 3.1.14 on 2024-05-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240529_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
